apiVersion: v1
kind: ConfigMap
metadata:
  name: meta-handler-config
data:
  AWS_REGION: "sa-east-1"
  SQS_INPUT_QUEUE_URL: "https://sqs.sa-east-1.amazonaws.com/ACCOUNT_ID/meta-received"
  SQS_TEXT_QUEUE_URL: "https://sqs.sa-east-1.amazonaws.com/ACCOUNT_ID/inbound-text"
  SQS_MEDIA_QUEUE_URL: "https://sqs.sa-east-1.amazonaws.com/ACCOUNT_ID/inbound-media"
