apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-gateway-config
data:
  AWS_REGION: "sa-east-1"
  SQS_INPUT_QUEUE_URL: "https://sqs.sa-east-1.amazonaws.com/ACCOUNT_ID/inbound-text"
  SQS_REPLY_QUEUE_URL: "https://sqs.sa-east-1.amazonaws.com/ACCOUNT_ID/outbound-reply"
  SQS_REPORT_QUEUE_URL: "https://sqs.sa-east-1.amazonaws.com/ACCOUNT_ID/report-received"
  OLLAMA_URL: "http://llm:11434"
  LLM_MODEL: "llama3.1:8b"
