apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment-internal.yaml
  - deployment-public.yaml
  - service-internal.yaml
  - service-public.yaml
  - ingress.yaml
  - hpa.yaml
