apiVersion: v1
kind: ConfigMap
metadata:
  name: output-service-config
data:
  AWS_REGION: "sa-east-1"
  SQS_INPUT_QUEUE_URL: "https://sqs.sa-east-1.amazonaws.com/ACCOUNT_ID/outbound-reply"
  GRAPH_API_BASE: "https://graph.facebook.com/v20.0"
  REDIS_URL: "redis://respuesta-redis.xxxx.ng.0001.sae1.cache.amazonaws.com:6379/0"
  HSM_TEMPLATE: "jornada_update"
  HSM_LANG: "es"
